disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count
  - trailing_whitespace
  - line_length
  - variable_name
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - force_https
  - empty_count
  - conditional_binding_cascade
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

custom_rules:
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
