source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

abstract_target 'defaults' do
    pod 'Decodable'
    pod 'HockeySDK'
    pod 'REMenu'

    target 'Dark Days'
    target 'Dark DaysTests'

end
